acpi: hest: Remove unused variable to avoid compiler warning
With GCC 16, the compilation fails with:

 acpi/hest/hest.c: In function ‘hest_test1’:
 acpi/hest/hest.c:790:18: error: variable ‘hest_type_11_count’ set but not used
  [-Werror=unused-but-set-variable=]
   790 |                  hest_type_11_count = 0;
       |                  ^~~~~~~~~~~~~~~~~~
 cc1: all warnings being treated as errors

Remove the unused variable to fix the problem.

Signed-off-by: Thomas Huth <thuth@redhat.com>