fwts_args: Silence compiler warning about unused "master_option_index"
With GCC 16, the compilation fails:

 fwts_args.c: In function 'fwts_args_parse':
 fwts_args.c:109:13: error: variable 'master_option_index' set but not used
  [-Werror=unused-but-set-variable=]
   109 |         int master_option_index;
       |             ^~~~~~~~~~~~~~~~~~~
 cc1: all warnings being treated as errors

Remove the unused code to fix the problem.

Signed-off-by: Thomas Huth <thuth@redhat.com>