acpi: crsdump: Fix printing of IRQ numbers
Clang complains when compiling this file:

 acpi/crsdump/crsdump.c:328:30: error: size argument in 'strlcat' call
  appears to be size of the source; expected the size of the destination
       [-Werror,-Wstrlcpy-strlcat-size]
   328 |                                 strlcat(buf, tmp, sizeof(tmp));
       |                                                   ~~~~~~~^~~~
 acpi/crsdump/crsdump.c:328:23: note: change size argument to be the size
  of the destination
   328 |                                 strlcat(buf, tmp, sizeof(tmp));
       |                                                   ^~~~~~~~~~~
       |                                                   sizeof(buf)

And indeed, this function currently fails to print any IRQ numbers.
Use the size of the destination buffer instead to fix the problem.

Fixes: 3f151922 ("Fix some strncpy/strcat gcc 8.2 warnings by using libbsd strlcpy/strlcat")
Signed-off-by: Thomas Huth <thuth@redhat.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>