lib: framework: Remove unused variable to avoid compiler warning
With GCC 16, the compilation fails with:

 fwts_framework.c: In function 'fwts_framework_show_tests':
 fwts_framework.c:325:13: error: variable 'total' set but not used
  [-Werror=unused-but-set-variable=]
   325 |         int total = 0;
       |             ^~~~~
 cc1: all warnings being treated as errors

Remove the unused variable to fix the problem.

Signed-off-by: Thomas Huth <thuth@redhat.com>