acpi: gpedump: Fix format string for BaseGpeNumber
When compiling this source code with Clang, the compiler complains:

acpi/gpedump/gpedump.c:142:4: error: format specifies type 'unsigned char'
 but the argument has type 'UINT16' (aka 'unsigned short') [-Werror,-Wformat]
  139 |  fwts_log_info_verbatim(fw,
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  140 |     "    Register %" PRIu32 ": (GPE 0x%2.2" PRIx8 "-0x%2.2" PRIx8 ")",
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  141 |     reg,
      |     ~~~~
  142 |     gpe_reg_info->BaseGpeNumber,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  143 |     gpe_reg_info->BaseGpeNumber + (ACPI_GPE_REGISTER_WIDTH - 1));
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And indeed, BaseGpeNumber is a 16 bit value in the ACPI_GPE_REGISTER_INFO
struct. Thus use a PRIx16 here to print these values.

Signed-off-by: Thomas Huth <thuth@redhat.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>