hotkey: fix const-correctness in hotkey_find_keymap
fwts_text_list_text() returns char *, so the explicit cast to
const char * was unnecessary and caused strstr() to return a
const char * that could not be assigned to char *ptr which is
later used to modify the string in place (*ptr = '\0').

hotkey/hotkey/hotkey.c: In function ‘hotkey_find_keymap’:
hotkey/hotkey/hotkey.c:205:34: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  205 |                         if ((ptr = strstr(text, "'")) != NULL)
      |                                 ^

Remove the unneeded const cast to fix the -Werror=discarded-qualifiers
build failure with newer GCC15.

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>