acpi: mcfg: Fix format string for pci_segment_group_number
When compiling this source with Clang, the compiler complains:

 acpi/mcfg/mcfg.c:202:59: error: format specifies type 'unsigned char' but the
  argument has type 'uint16_t' (aka 'unsigned short') [-Werror,-Wformat]

And indeed, pci_segment_group_number is a 16 bit value in the struct
fwts_acpi_mcfg_configuration, and it is also a 16 bit value according
to the description of the MCFG table in the "PCI Firmware Specification",
so we should use PRIu16 here to print the value.

Signed-off-by: Thomas Huth <thuth@redhat.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>