fwts_modprobe: Remove unused sys_finit_module() and sys_delete_module()
These functions are not used anymore since commit e34d0663d94387e7
("lib: modprobe: add checking the compressed zst module format").
Since they are marked as "static inline", Clang complains here:

 fwts_modprobe.c:118:19: error: unused function 'sys_finit_module'
  [-Werror,-Wunused-function]
   118 | static inline int sys_finit_module(
       |                   ^~~~~~~~~~~~~~~~
 fwts_modprobe.c:131:19: error: unused function 'sys_delete_module'
  [-Werror,-Wunused-function]
   131 | static inline int sys_delete_module(
       |                   ^~~~~~~~~~~~~~~~~

Thus let's simply delete these functions now to allow Clang to compile
this file without warnings.

Fixes: e34d0663 ("lib: modprobe: add checking the compressed zst module format")
Signed-off-by: Thomas Huth <thuth@redhat.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>